# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: fhusseiniPool

steps:
- script: echo "This is the new world!"
  displayName: 'Run a one-line script'
